# Generated by Django 5.1.3 on 2024-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
    ]
