# Generated by Django 5.1.3 on 2024-12-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
